server:
  port: 8081
  context-path: /antimage


spring:
  application:
    name: antimage
  cloud:
      config:
        server:
          git:
            uri: https://github.com/bigcong/antimage.git
          searchPaths: config-repository

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8081/antimage/eureka/

